const COUNTRIES_FR = [
  { value: "Afghanistan", symbol: "🇦🇫 Afghanistan" },
  { value: "Afrique du Sud", symbol: "🇿🇦 Afrique du Sud" },
  { value: "Albanie", symbol: "🇦🇱 Albanie" },
  { value: "Algérie", symbol: "🇩🇿 Algérie" },
  { value: "Allemagne", symbol: "🇩🇪 Allemagne" },
  { value: "Andorre", symbol: "🇦🇩 Andorre" },
  { value: "Angola", symbol: "🇦🇴 Angola" },
  { value: "Anguilla", symbol: "🇦🇮 Anguilla" },
  { value: "Antarctique", symbol: "🇦🇶 Antarctique" },
  { value: "Antigua & Barbuda", symbol: "🇦🇬 Antigua-et-Barbuda" },
  { value: "Arabie saoudite", symbol: "🇸🇦 Arabie saoudite" },
  { value: "Argentine", symbol: "🇦🇷 Argentine" },
  { value: "Arménie", symbol: "🇦🇲 Arménie" },
  { value: "Aruba", symbol: "🇦🇼 Aruba" },
  { value: "Australie", symbol: "🇦🇺 Australie" },
  { value: "Autriche", symbol: "🇦🇹 Autriche" },
  { value: "Azerbaïdjan", symbol: "🇦🇿 Azerbaïdjan" },
  { value: "Bahamas", symbol: "🇧🇸 Bahamas" },
  { value: "Bahreïn", symbol: "🇧🇭 Bahreïn" },
  { value: "Bangladesh", symbol: "🇧🇩 Bangladesh" },
  { value: "Barbade", symbol: "🇧🇧 Barbade" },
  { value: "Biélorussie", symbol: "🇧🇾 Biélorussie" },
  { value: "Belgique", symbol: "🇧🇪 Belgique" },
  { value: "Belize", symbol: "🇧🇿 Belize" },
  { value: "Bénin", symbol: "🇧🇯 Bénin" },
  { value: "Bermudes", symbol: "🇧🇲 Bermudes" },
  { value: "Bhoutan", symbol: "🇧🇹 Bhoutan" },
  { value: "Bolivie", symbol: "🇧🇴 Bolivie" },
  { value: "Bosnie-Herzegovine", symbol: "🇧🇦 Bosnie-Herzégovine" },
  { value: "Botswana", symbol: "🇧🇼 Botswana" },
  { value: "Brésil", symbol: "🇧🇷 Brésil" },

  { value: "Bruneï", symbol: "🇧🇳 Bruneï" },
  { value: "Bulgarie", symbol: "🇧🇬 Bulgarie" },
  { value: "Burkina Faso", symbol: "🇧🇫 Burkina Faso" },
  { value: "Burundi", symbol: "🇧🇮 Burundi" },
  { value: "Cambodge", symbol: "🇰🇭 Cambodge" },
  { value: "Cameroun", symbol: "🇨🇲 Cameroun" },
  { value: "Canada", symbol: "🇨🇦 Canada" },
  { value: "Cap-Vert", symbol: "🇨🇻 Cap-Vert" },
  { value: "Ceuta & Melilla", symbol: "🇪🇦 Ceuta et Melilla" },
  { value: "TChad", symbol: "🇹🇩 Tchad" },
  { value: "Chili", symbol: "🇨🇱 Chili" },
  { value: "Chine", symbol: "🇨🇳 Chine" },

  { value: "Colombie", symbol: "🇨🇴 Colombie" },
  { value: "Comores", symbol: "🇰🇲 Comores" },
  { value: "Congo-Brazzaville", symbol: "🇨🇬 Congo-Brazzaville" },
  { value: "Congo-Kinshasa", symbol: "🇨🇩 Congo-Kinshasa" },
  { value: "Corée du Nord", symbol: "🇰🇵 Corée du Nord" },
  { value: "Corée du Sud", symbol: "🇰🇷 Corée du Sud" },
  { value: "Costa Rica", symbol: "🇨🇷 Costa Rica" },
  { value: "Croatie", symbol: "🇭🇷 Croatie" },
  { value: "Cuba", symbol: "🇨🇺 Cuba" },
  { value: "Curaçao", symbol: "🇨🇼 Curaçao" },
  { value: "Chypre", symbol: "🇨🇾 Chypre" },
  { value: "Côte d’Ivoire", symbol: "🇨🇮 Côte d'Ivoire" },
  { value: "Danemark", symbol: "🇩🇰 Danemark" },
  { value: "Diego Garcia", symbol: "🇩🇬 Diego Garcia" },
  { value: "Djibouti", symbol: "🇩🇯 Djibouti" },
  { value: "Dominique", symbol: "🇩🇲 Dominique" },
  {
    value: "République dominicaine",
    symbol: "🇩🇴 République dominicaine",
  },
  { value: "Egypte", symbol: "🇪🇬 Egypte" },
  { value: "Emirats Arabes Unis", symbol: "🇦🇪 Emirats Arabes Unis" },
  { value: "Equateur", symbol: "🇪🇨 Equateur" },
  { value: "Erythrée", symbol: "🇪🇷 Erythrée" },
  { value: "Estonie", symbol: "🇪🇪 Estonie" },
  { value: "Espagne", symbol: "🇪🇸 Espagne" },
  { value: "Etats-Unis", symbol: "🇺🇸 Etats-Unis" },
  { value: "Ethiopie", symbol: "🇪🇹 Ethiopie" },
  { value: "Fidji", symbol: "🇫🇯 Fidji" },
  { value: "Finlande", symbol: "🇫🇮 Finlande" },
  { value: "France", symbol: "🇫🇷 France" },

  { value: "Gabon", symbol: "🇬🇦 Gabon" },
  { value: "Gambia", symbol: "🇬🇲 Gambie" },
  { value: "Georgia", symbol: "🇬🇪 Géorgie" },
  { value: "Ghana", symbol: "🇬🇭 Ghana" },
  { value: "Gibraltar", symbol: "🇬🇮 Gibraltar" },
  { value: "Greece", symbol: "🇬🇷 Grèce" },
  { value: "Greenland", symbol: "🇬🇱 Groenland" },
  { value: "Grenada", symbol: "🇬🇩 Grenade" },
  { value: "Guadeloupe", symbol: "🇬🇵 Guadeloupe" },
  { value: "Guam", symbol: "🇬🇺 Guam" },
  { value: "Guatemala", symbol: "🇬🇹 Guatemala" },
  { value: "Guernsey", symbol: "🇬🇬 Guernesey" },
  { value: "Guinea", symbol: "🇬🇳 Guinée" },
  { value: "Guinea-Bissau", symbol: "🇬🇼 Guinée-Bissau" },
  { value: "Guinée équatoriale", symbol: "🇬🇶 Guinée équatoriale" },
  { value: "Guyana", symbol: "🇬🇾 Guyana" },
  { value: "Guyane française", symbol: "🇬🇫 Guyane française" },
  { value: "Haiti", symbol: "🇭🇹 Haïti" },
  { value: "Honduras", symbol: "🇭🇳 Honduras" },
  { value: "Hong Kong", symbol: "🇭🇰 Hong Kong" },
  { value: "Hongrie", symbol: "🇭🇺 Hongrie" },
  { value: "Iles Åland", symbol: "🇦🇽 Îles Åland" },
  { value: "Ile de l'Ascension", symbol: "🇦🇨 Île de l'Ascension" },
  { value: "Ile Bouvet", symbol: "🇧🇻 Île Bouvet" },
  { value: "Iles Caïmans", symbol: "🇰🇾 Îles Caïmans" },
  { value: "Iles Canaries", symbol: "🇮🇨 Îles Canaries" },
  { value: "Ile Christmas", symbol: "🇨🇽 Île Christmas" },
  { value: "Ile Clipperton", symbol: "🇨🇵 Île Clipperton" },
  { value: "Iles Cocos (Keeling)", symbol: "🇨🇨 Îles Cocos (Keeling)" },
  { value: "Iles Cook", symbol: "🇨🇰 Îles Cook" },
  { value: "Iles Féroé", symbol: "🇫🇴 Îles Féroé" },
  {
    value: "Iles Heard-et-MacDonald",
    symbol: "🇭🇲 Îles Heard-et-MacDonald",
  },
  { value: "Iles Malouines", symbol: "🇫🇰 Îles Malouines" },
  { value: "Ile de Man", symbol: "🇮🇲 Île de Man" },
  {
    value: "Iles Mariannes du Nord",
    symbol: "🇲🇵 Îles Mariannes du Nord",
  },
  { value: "Iles Marshall", symbol: "🇲🇭 Îles Marshall" },
  {
    value: "Iles mineures éloignées des Etats-Unis",
    symbol: "🇺🇲 Îles mineures éloignées des Etats-Unis",
  },
  { value: "Ile Norfolk", symbol: "🇳🇫 Île Norfolk" },
  { value: "Iles Pitcairn", symbol: "🇵🇳 Îles Pitcairn" },
  { value: "Iles Salomon", symbol: "🇸🇧 Îles Salomon" },
  {
    value: "Iles Turques-et-Caïques",
    symbol: "🇹🇨 Îles Turques-et-Caïques",
  },
  {
    value: "Iles Vierges américaines",
    symbol: "🇻🇮 Îles Vierges américaines",
  },
  {
    value: "Iles Vierges britanniques",
    symbol: "🇻🇬 Îles Vierges britanniques",
  },
  { value: "Islande", symbol: "🇮🇸 Islande" },
  { value: "Indie", symbol: "🇮🇳 Inde" },
  { value: "Indonésie", symbol: "🇮🇩 Indonésie" },
  { value: "Iran", symbol: "🇮🇷 Iran" },
  { value: "Irak", symbol: "🇮🇶 Irak" },
  { value: "Irlande", symbol: "🇮🇪 Irlande" },
  { value: "Israël", symbol: "🇮🇱 Israël" },
  { value: "Italie", symbol: "🇮🇹 Italie" },
  { value: "Jamaïque", symbol: "🇯🇲 Jamaïque" },
  { value: "Japon", symbol: "🇯🇵 Japon" },
  { value: "Jersey", symbol: "🇯🇪 Jersey" },
  { value: "Jordanie", symbol: "🇯🇴 Jordanie" },
  { value: "Kazakhstan", symbol: "🇰🇿 Kazakhstan" },
  { value: "Kenya", symbol: "🇰🇪 Kenya" },
  { value: "Kiribati", symbol: "🇰🇮 Kiribati" },
  { value: "Kosovo", symbol: "🇽🇰 Kosovo" },
  { value: "Koweït", symbol: "🇰🇼 Koweït" },
  { value: "Kirghizistan", symbol: "🇰🇬 Kirghizistan" },
  { value: "Laos", symbol: "🇱🇦 Laos" },
  { value: "Lettonie", symbol: "🇱🇻 Lettonie" },
  { value: "Liban", symbol: "🇱🇧 Liban" },
  { value: "Lesotho", symbol: "🇱🇸 Lesotho" },
  { value: "Libéria", symbol: "🇱🇷 Libéria" },
  { value: "Libye", symbol: "🇱🇾 Libye" },
  { value: "Liechtenstein", symbol: "🇱🇮 Liechtenstein" },
  { value: "Lithuanie", symbol: "🇱🇹 Lituanie" },
  { value: "Luxembourg", symbol: "🇱🇺 Luxembourg" },
  { value: "Macao", symbol: "🇲🇴 Macao" },
  { value: "Macédoine", symbol: "🇲🇰 Macédoine" },
  { value: "Madagascar", symbol: "🇲🇬 Madagascar" },
  { value: "Malawi", symbol: "🇲🇼 Malawi" },
  { value: "Malaisie", symbol: "🇲🇾 Malaisie" },
  { value: "Maldives", symbol: "🇲🇻 Maldives" },
  { value: "Mali", symbol: "🇲🇱 Mali" },
  { value: "Malte", symbol: "🇲🇹 Malte" },
  { value: "Martinique", symbol: "🇲🇶 Martinique" },
  { value: "Mauritanie", symbol: "🇲🇷 Mauritanie" },
  { value: "Maurice", symbol: "🇲🇺 Maurice" },
  { value: "Mayotte", symbol: "🇾🇹 Mayotte" },
  { value: "Mexique", symbol: "🇲🇽 Mexique" },
  { value: "Micronésie", symbol: "🇫🇲 Micronésie" },
  { value: "Moldavie", symbol: "🇲🇩 Moldavie" },
  { value: "Monaco", symbol: "🇲🇨 Monaco" },
  { value: "Mongolie", symbol: "🇲🇳 Mongolie" },
  { value: "Monténégro", symbol: "🇲🇪 Monténégro" },
  { value: "Montserrat", symbol: "🇲🇸 Montserrat" },
  { value: "Maroc", symbol: "🇲🇦 Maroc" },
  { value: "Mozambique", symbol: "🇲🇿 Mozambique" },
  { value: "Myanmar (Birmanie)", symbol: "🇲🇲 Myanmar (Birmanie)" },
  { value: "Namibie", symbol: "🇳🇦 Namibie" },
  { value: "Nauru", symbol: "🇳🇷 Nauru" },
  { value: "Népal", symbol: "🇳🇵 Népal" },
  { value: "Nicaragua", symbol: "🇳🇮 Nicaragua" },
  { value: "Niger", symbol: "🇳🇪 Niger" },
  { value: "Nigéria", symbol: "🇳🇬 Nigéria" },
  { value: "Niue", symbol: "🇳🇺 Niue" },
  { value: "Norvège", symbol: "🇳🇴 Norvège" },
  { value: "Nouvelle-Calédonie", symbol: "🇳🇨 Nouvelle-Calédonie" },
  { value: "Nouvelle-Zélande", symbol: "🇳🇿 Nouvelle-Zélande" },
  { value: "Oman", symbol: "🇴🇲 Oman" },
  { value: "Pakistan", symbol: "🇵🇰 Pakistan" },
  { value: "Palaos", symbol: "🇵🇼 Palaos" },
  { value: "Palestine", symbol: "🇵🇸 Palestine" },
  { value: "Panama", symbol: "🇵🇦 Panama" },
  {
    value: "Papouasie-Nouvelle-Guinée",
    symbol: "🇵🇬 Papouasie-Nouvelle-Guinée",
  },
  { value: "Paraguay", symbol: "🇵🇾 Paraguay" },
  { value: "Pays-Bas", symbol: "🇳🇱 Pays-Bas" },
  { value: "Pays-Bas caribéens", symbol: "🇧🇶 Pays-Bas caribéens" },
  { value: "Pérou", symbol: "🇵🇪 Pérou" },
  { value: "Philippines", symbol: "🇵🇭 Philippines" },
  { value: "Pologne", symbol: "🇵🇱 Pologne" },
  { value: "Polynésie française", symbol: "🇵🇫 Polynésie française" },
  { value: "Portugal", symbol: "🇵🇹 Portugal" },
  { value: "Porto Rico", symbol: "🇵🇷 Porto Rico" },
  { value: "Qatar", symbol: "🇶🇦 Qatar" },
  {
    value: " République Centrafricaine",
    symbol: "🇨🇫 République Centrafricaine",
  },
  { value: "République Tchèque", symbol: "🇨🇿 République Tchèque" },
  { value: "Roumanie", symbol: "🇷🇴 Roumanie" },
  { value: "Royaume-Uni", symbol: "🇬🇧 Royaume-Uni" },
  { value: "Russie", symbol: "🇷🇺 Russie" },
  { value: "Rwanda", symbol: "🇷🇼 Rwanda" },
  { value: "Réunion", symbol: "🇷🇪 Réunion" },
  { value: "Sahara occidental", symbol: "🇪🇭 Sahara occidental" },
  { value: "St. Barthélemy", symbol: "🇧🇱 Saint-Barthélemy" },
  { value: "St. Helena", symbol: "🇸🇭 Sainte-Hélène" },
  { value: "St. Kitts & Nevis", symbol: "🇰🇳 Saint-Kitts-et-Nevis" },
  { value: "St. Lucia", symbol: "🇱🇨 Sainte-Lucie" },
  { value: "Saint-Marin", symbol: "🇸🇲 Saint-Marin" },
  { value: "St. Martin", symbol: "🇲🇫 Saint-Martin" },
  {
    value: "Saint-Martin (partie néerlandaise)",
    symbol: "🇸🇽 Saint-Martin (partie néerlandaise)",
  },
  {
    value: "St. Pierre & Miquelon",
    symbol: "🇵🇲 Saint-Pierre-et-Miquelon",
  },
  {
    value: "St. Vincent & Grenadines",
    symbol: "🇻🇨 Saint-Vincent-et-les-Grenadines",
  },
  { value: "Salvador", symbol: "🇸🇻 Salvador" },
  { value: "Samoa", symbol: "🇼🇸 Samoa" },
  { value: "Samoa américaines", symbol: "🇦🇸 Samoa américaines" },
  { value: "Sénégal", symbol: "🇸🇳 Sénégal" },
  { value: "Serbie", symbol: "🇷🇸 Serbie" },
  { value: "Seychelles", symbol: "🇸🇨 Seychelles" },
  { value: "Sierra Leone", symbol: "🇸🇱 Sierra Leone" },
  { value: "Singapour", symbol: "🇸🇬 Singapour" },
  { value: "Slovaquie", symbol: "🇸🇰 Slovaquie" },
  { value: "Slovénie", symbol: "🇸🇮 Slovénie" },
  { value: "Somalie", symbol: "🇸🇴 Somalie" },
  {
    value: "South Georgia & South Sandwich Islands",
    symbol: "🇬🇸 Géorgie du Sud et îles Sandwich du Sud",
  },
  { value: "Soudan du Sud", symbol: "🇸🇸 Soudan du Sud" },
  { value: "Sri Lanka", symbol: "🇱🇰 Sri Lanka" },

  { value: "Soudan", symbol: "🇸🇩 Soudan" },
  { value: "Suriname", symbol: "🇸🇷 Suriname" },
  { value: "Svalbard & Jan Mayen", symbol: "🇸🇯 Svalbard et Jan Mayen" },
  { value: "Swaziland", symbol: "🇸🇿 Swaziland" },
  { value: "Suède", symbol: "🇸🇪 Suède" },
  { value: "Suisse", symbol: "🇨🇭 Suisse" },
  { value: "Syrie", symbol: "🇸🇾 Syrie" },
  { value: "Sao Tomé & Príncipe", symbol: "🇸🇹 Sao Tomé-et-Principe" },
  { value: "Taiwan", symbol: "🇹🇼 Taïwan" },
  { value: "Tadjikistan", symbol: "🇹🇯 Tadjikistan" },
  { value: "Tanzanie", symbol: "🇹🇿 Tanzanie" },
  { value: "Thaïlande", symbol: "🇹🇭 Thaïlande" },
  {
    value: "Terres australes françaises",
    symbol: "🇹🇫 Terres australes françaises",
  },
  {
    value: "Territoire britannique de l'océan Indien",
    symbol: "🇮🇴 Territoire britannique de l'océan Indien",
  },
  { value: "Timor oriental", symbol: "🇹🇱 Timor oriental" },
  { value: "Togo", symbol: "🇹🇬 Togo" },
  { value: "Tokelau", symbol: "🇹🇰 Tokelau" },
  { value: "Tonga", symbol: "🇹🇴 Tonga" },
  { value: "Trinité-et-Tobago", symbol: "🇹🇹 Trinité-et-Tobago" },
  { value: "Tristan da Cunha", symbol: "🇹🇦 Tristan da Cunha" },
  { value: "Tunisie", symbol: "🇹🇳 Tunisie" },
  { value: "Turquie", symbol: "🇹🇷 Turquie" },
  { value: "Turkménistan", symbol: "🇹🇲 Turkménistan" },
  { value: "Tuvalu", symbol: "🇹🇻 Tuvalu" },
  { value: "Ouganda", symbol: "🇺🇬 Ouganda" },
  { value: "Ukraine", symbol: "🇺🇦 Ukraine" },
  { value: "Uruguay", symbol: "🇺🇾 Uruguay" },
  { value: "Ouzbékistan", symbol: "🇺🇿 Ouzbékistan" },
  { value: "Vanuatu", symbol: "🇻🇺 Vanuatu" },
  { value: "Cité du Vatican", symbol: "🇻🇦 Cité du Vatican" },
  { value: "Venezuela", symbol: "🇻🇪 Venezuela" },
  { value: "Vietnam", symbol: "🇻🇳 Vietnam" },
  { value: "Wallis & Futuna", symbol: "🇼🇫 Wallis et Futuna" },
  { value: "Yémen", symbol: "🇾🇪 Yémen" },
  { value: "Zambie", symbol: "🇿🇲 Zambie" },
  { value: "Zimbabwe", symbol: "🇿🇼 Zimbabwe" },
];

const COUNTRIES_EN = [
  { value: "Afghanistan", symbol: "🇦🇫 Afghanistan" },
  { value: "Albania", symbol: "🇦🇱 Albania" },
  { value: "Algeria", symbol: "🇩🇿 Algeria" },
  { value: "Åland Islands", symbol: "🇦🇽 Åland Islands" },
  { value: "Andorra", symbol: "🇦🇩 Andorra" },
  { value: "Angola", symbol: "🇦🇴 Angola" },
  { value: "Anguilla", symbol: "🇦🇮 Anguilla" },
  { value: "Antarctica", symbol: "🇦🇶 Antarctica" },
  { value: "Antigua & Barbuda", symbol: "🇦🇬 Antigua & Barbuda" },
  { value: "Saudi Arabia", symbol: "🇸🇦 Saudi Arabia" },
  { value: "Argentina", symbol: "🇦🇷 Argentina" },
  { value: "Armenia", symbol: "🇦🇲 Armenia" },
  { value: "Aruba", symbol: "🇦🇼 Aruba" },
  { value: "Ascension Island", symbol: "🇦🇨 Ascension Island" },
  { value: "Australia", symbol: "🇦🇺 Australia" },
  { value: "Austria", symbol: "🇦🇹 Austria" },
  { value: "Azerbaijan", symbol: "🇦🇿 Azerbaijan" },
  { value: "Bahamas", symbol: "🇧🇸 Bahamas" },
  { value: "Bahrain", symbol: "🇧🇭 Bahrain" },
  { value: "Bangladesh", symbol: "🇧🇩 Bangladesh" },
  { value: "Barbados", symbol: "🇧🇧 Barbados" },
  { value: "Belarus", symbol: "🇧🇾 Belarus" },
  { value: "Belgium", symbol: "🇧🇪 Belgium" },
  { value: "Belize", symbol: "🇧🇿 Belize" },
  { value: "Benin", symbol: "🇧🇯 Benin" },
  { value: "Bermuda", symbol: "🇧🇲 Bermuda" },
  { value: "Bhutan", symbol: "🇧🇹 Bhutan" },
  { value: "Bolivia", symbol: "🇧🇴 Bolivia" },
  { value: "Bosnia & Herzegovina", symbol: "🇧🇦 Bosnia & Herzegovina" },
  { value: "Botswana", symbol: "🇧🇼 Botswana" },
  { value: "Bouvet Island", symbol: "🇧🇻 Bouvet Island" },
  { value: "Brazil", symbol: "🇧🇷 Brazil" },
  {
    value: "British Indian Ocean Territory",
    symbol: "🇮🇴 British Indian Ocean Territory",
  },
  { value: "British Virgin Islands", symbol: "🇻🇬 British Virgin Islands" },
  { value: "Brunei", symbol: "🇧🇳 Brunei" },
  { value: "Bulgaria", symbol: "🇧🇬 Bulgaria" },
  { value: "Burkina Faso", symbol: "🇧🇫 Burkina Faso" },
  { value: "Burundi", symbol: "🇧🇮 Burundi" },
  { value: "Cambodia", symbol: "🇰🇭 Cambodia" },
  { value: "Cameroon", symbol: "🇨🇲 Cameroon" },
  { value: "Canada", symbol: "🇨🇦 Canada" },
  { value: "Canary Islands", symbol: "🇮🇨 Canary Islands" },
  { value: "Cape Verde", symbol: "🇨🇻 Cape Verde" },
  { value: "Caribbean Netherlands", symbol: "🇧🇶 Caribbean Netherlands" },
  { value: "Cayman Islands", symbol: "🇰🇾 Cayman Islands" },
  { value: "Central African Republic", symbol: "🇨🇫 Central African Republic" },
  { value: "Ceuta & Melilla", symbol: "🇪🇦 Ceuta & Melilla" },
  { value: "Chad", symbol: "🇹🇩 Chad" },
  { value: "Chile", symbol: "🇨🇱 Chile" },
  { value: "China", symbol: "🇨🇳 China" },
  { value: "Christmas Island", symbol: "🇨🇽 Christmas Island" },
  { value: "Clipperton Island", symbol: "🇨🇵 Clipperton Island" },
  { value: "Cocos (Keeling) Islands", symbol: "🇨🇨 Cocos (Keeling) Islands" },
  { value: "Colombia", symbol: "🇨🇴 Colombia" },
  { value: "Comoros", symbol: "🇰🇲 Comoros" },
  { value: "Congo - Brazzaville", symbol: "🇨🇬 Congo-Brazzaville" },
  { value: "Congo - Kinshasa", symbol: "🇨🇩 Congo-Kinshasa" },
  { value: "Cook Islands", symbol: "🇨🇰 Cook Islands" },
  { value: "Costa Rica", symbol: "🇨🇷 Costa Rica" },
  { value: "Croatia", symbol: "🇭🇷 Croatia" },
  { value: "Cuba", symbol: "🇨🇺 Cuba" },
  { value: "Curaçao", symbol: "🇨🇼 Curaçao" },
  { value: "Cyprus", symbol: "🇨🇾 Cyprus" },
  { value: "Czechia", symbol: "🇨🇿 Czechia" },
  { value: "Côte d’Ivoire", symbol: "🇨🇮 Côte d'Ivoire" },
  { value: "Denmark", symbol: "🇩🇰 Denmark" },
  { value: "Diego Garcia", symbol: "🇩🇬 Diego Garcia" },
  { value: "Djibouti", symbol: "🇩🇯 Djibouti" },
  { value: "Dominica", symbol: "🇩🇲 Dominica" },
  { value: "Dominican Republic", symbol: "🇩🇴 Dominican Republic" },
  { value: "Ecuador", symbol: "🇪🇨 Ecuador" },
  { value: "Egypt", symbol: "🇪🇬 Egypt" },
  { value: "El Salvador", symbol: "🇸🇻 El Salvador" },
  { value: "Equatorial Guinea", symbol: "🇬🇶 Equatorial Guinea" },
  { value: "Eritrea", symbol: "🇪🇷 Eritrea" },
  { value: "Estonia", symbol: "🇪🇪 Estonia" },
  { value: "United States", symbol: "🇺🇸 United States" },
  { value: "Ethiopia", symbol: "🇪🇹 Ethiopia" },
  { value: "Falkland Islands", symbol: "🇫🇰 Falkland Islands" },
  { value: "Faroe Islands", symbol: "🇫🇴 Faroe Islands" },
  { value: "Fiji", symbol: "🇫🇯 Fiji" },
  { value: "Finland", symbol: "🇫🇮 Finland" },
  { value: "France", symbol: "🇫🇷 France" },
  { value: "French Guiana", symbol: "🇬🇫 French Guiana" },
  { value: "French Polynesia", symbol: "🇵🇫 French Polynesia" },
  {
    value: "French Southern Territories",
    symbol: "🇹🇫 French Southern Territories",
  },
  { value: "Gabon", symbol: "🇬🇦 Gabon" },
  { value: "Gambia", symbol: "🇬🇲 Gambia" },
  { value: "Georgia", symbol: "🇬🇪 Georgia" },
  { value: "Germany", symbol: "🇩🇪 Germany" },
  { value: "Ghana", symbol: "🇬🇭 Ghana" },
  { value: "Gibraltar", symbol: "🇬🇮 Gibraltar" },
  { value: "Greece", symbol: "🇬🇷 Greece" },
  { value: "Greenland", symbol: "🇬🇱 Greenland" },
  { value: "Grenada", symbol: "🇬🇩 Grenada" },
  { value: "Guadeloupe", symbol: "🇬🇵 Guadeloupe" },
  { value: "Guam", symbol: "🇬🇺 Guam" },
  { value: "Guatemala", symbol: "🇬🇹 Guatemala" },
  { value: "Guernsey", symbol: "🇬🇬 Guernsey" },
  { value: "Guinea", symbol: "🇬🇳 Guinea" },
  { value: "Guinea-Bissau", symbol: "🇬🇼 Guinea-Bissau" },
  { value: "Guyana", symbol: "🇬🇾 Guyana" },
  { value: "Haiti", symbol: "🇭🇹 Haiti" },
  { value: "Heard & McDonald Islands", symbol: "🇭🇲 Heard & McDonald Islands" },
  { value: "Honduras", symbol: "🇭🇳 Honduras" },
  { value: "Hong Kong", symbol: "🇭🇰 Hong Kong" },
  { value: "Hungary", symbol: "🇭🇺 Hungary" },
  { value: "Isle of Man", symbol: "🇮🇲 Isle of Man" },
  { value: "Iceland", symbol: "🇮🇸 Iceland" },
  { value: "India", symbol: "🇮🇳 India" },
  { value: "Indonesia", symbol: "🇮🇩 Indonesia" },
  { value: "Iran", symbol: "🇮🇷 Iran" },
  { value: "Iraq", symbol: "🇮🇶 Iraq" },
  { value: "Ireland", symbol: "🇮🇪 Ireland" },
  { value: "Israel", symbol: "🇮🇱 Israel" },
  { value: "Italy", symbol: "🇮🇹 Italy" },
  { value: "Jamaica", symbol: "🇯🇲 Jamaica" },
  { value: "Japan", symbol: "🇯🇵 Japan" },
  { value: "Jersey", symbol: "🇯🇪 Jersey" },
  { value: "Jordan", symbol: "🇯🇴 Jordan" },
  { value: "Kazakhstan", symbol: "🇰🇿 Kazakhstan" },
  { value: "Kenya", symbol: "🇰🇪 Kenya" },
  { value: "Kiribati", symbol: "🇰🇮 Kiribati" },
  { value: "Kosovo", symbol: "🇽🇰 Kosovo" },
  { value: "Kuwait", symbol: "🇰🇼 Kuwait" },
  { value: "Kyrgyzstan", symbol: "🇰🇬 Kyrgyzstan" },
  { value: "Laos", symbol: "🇱🇦 Laos" },
  { value: "Latvia", symbol: "🇱🇻 Latvia" },
  { value: "Lebanon", symbol: "🇱🇧 Lebanon" },
  { value: "Lesotho", symbol: "🇱🇸 Lesotho" },
  { value: "Liberia", symbol: "🇱🇷 Liberia" },
  { value: "Libya", symbol: "🇱🇾 Libya" },
  { value: "Liechtenstein", symbol: "🇱🇮 Liechtenstein" },
  { value: "Lithuania", symbol: "🇱🇹 Lithuania" },
  { value: "Luxembourg", symbol: "🇱🇺 Luxembourg" },
  { value: "Macau", symbol: "🇲🇴 Macao" },
  { value: "Macedonia", symbol: "🇲🇰 Macedonia" },
  { value: "Madagascar", symbol: "🇲🇬 Madagascar" },
  { value: "Malawi", symbol: "🇲🇼 Malawi" },
  { value: "Malaysia", symbol: "🇲🇾 Malaysia" },
  { value: "Maldives", symbol: "🇲🇻 Maldives" },
  { value: "Mali", symbol: "🇲🇱 Mali" },
  { value: "Malta", symbol: "🇲🇹 Malta" },
  { value: "Marshall Islands", symbol: "🇲🇭 Marshall Islands" },
  { value: "Martinique", symbol: "🇲🇶 Martinique" },
  { value: "Mauritania", symbol: "🇲🇷 Mauritania" },
  { value: "Mauritius", symbol: "🇲🇺 Mauritius" },
  { value: "Mayotte", symbol: "🇾🇹 Mayotte" },
  { value: "Mexico", symbol: "🇲🇽 Mexico" },
  { value: "Micronesia", symbol: "🇫🇲 Micronesia" },
  { value: "Moldova", symbol: "🇲🇩 Moldova" },
  { value: "Monaco", symbol: "🇲🇨 Monaco" },
  { value: "Mongolia", symbol: "🇲🇳 Mongolia" },
  { value: "Montenegro", symbol: "🇲🇪 Montenegro" },
  { value: "Montserrat", symbol: "🇲🇸 Montserrat" },
  { value: "Morocco", symbol: "🇲🇦 Morocco" },
  { value: "Mozambique", symbol: "🇲🇿 Mozambique" },
  { value: "Myanmar (Burma)", symbol: "🇲🇲 Myanmar (Burma)" },
  { value: "Namibia", symbol: "🇳🇦 Namibia" },
  { value: "Nauru", symbol: "🇳🇷 Nauru" },
  { value: "Nepal", symbol: "🇳🇵 Nepal" },
  { value: "Netherlands", symbol: "🇳🇱 Netherlands" },
  { value: "New Caledonia", symbol: "🇳🇨 New Caledonia" },
  { value: "New Zealand", symbol: "🇳🇿 New Zealand" },
  { value: "Nicaragua", symbol: "🇳🇮 Nicaragua" },
  { value: "Niger", symbol: "🇳🇪 Niger" },
  { value: "Nigeria", symbol: "🇳🇬 Nigeria" },
  { value: "Niue", symbol: "🇳🇺 Niue" },
  { value: "Norfolk Island", symbol: "🇳🇫 Norfolk Island" },
  { value: "North Korea", symbol: "🇰🇵 North Korea" },
  { value: "Northern Mariana Islands", symbol: "🇲🇵 Northern Mariana Islands" },
  { value: "Norway", symbol: "🇳🇴 Norway" },
  { value: "Oman", symbol: "🇴🇲 Oman" },
  { value: "Pakistan", symbol: "🇵🇰 Pakistan" },
  { value: "Palau", symbol: "🇵🇼 Palau" },
  { value: "Palestinian Territories", symbol: "🇵🇸 Palestinian Territories" },
  { value: "Panama", symbol: "🇵🇦 Panama" },
  { value: "Papua New Guinea", symbol: "🇵🇬 Papua New Guinea" },
  { value: "Paraguay", symbol: "🇵🇾 Paraguay" },
  { value: "Peru", symbol: "🇵🇪 Peru" },
  { value: "Philippines", symbol: "🇵🇭 Philippines" },
  { value: "Pitcairn Islands", symbol: "🇵🇳 Pitcairn Islands" },
  { value: "Poland", symbol: "🇵🇱 Poland" },
  { value: "Portugal", symbol: "🇵🇹 Portugal" },
  { value: "Puerto Rico", symbol: "🇵🇷 Puerto Rico" },
  { value: "Qatar", symbol: "🇶🇦 Qatar" },
  { value: "Romania", symbol: "🇷🇴 Romania" },
  { value: "Russia", symbol: "🇷🇺 Russia" },
  { value: "Rwanda", symbol: "🇷🇼 Rwanda" },
  { value: "Réunion", symbol: "🇷🇪 Réunion" },
  { value: "Samoa", symbol: "🇼🇸 Samoa" },
  { value: "San Marino", symbol: "🇸🇲 San Marino" },
  { value: "Senegal", symbol: "🇸🇳 Senegal" },
  { value: "Serbia", symbol: "🇷🇸 Serbia" },
  { value: "Seychelles", symbol: "🇸🇨 Seychelles" },
  { value: "Sierra Leone", symbol: "🇸🇱 Sierra Leone" },
  { value: "Singapore", symbol: "🇸🇬 Singapore" },
  { value: "Sint Maarten", symbol: "🇸🇽 Sint Maarten" },
  { value: "Slovakia", symbol: "🇸🇰 Slovakia" },
  { value: "Slovenia", symbol: "🇸🇮 Slovenia" },
  { value: "Solomon Islands", symbol: "🇸🇧 Solomon Islands" },
  { value: "Somalia", symbol: "🇸🇴 Somalia" },
  { value: "South Africa", symbol: "🇿🇦 South Africa" },
  {
    value: "South Georgia & South Sandwich Islands",
    symbol: "🇬🇸 South Georgia & South Sandwich Islands",
  },
  { value: "South Korea", symbol: "🇰🇷 South Korea" },

  { value: "South Sudan", symbol: "🇸🇸 South Sudan" },
  { value: "Spain", symbol: "🇪🇸 Spain" },
  { value: "Sri Lanka", symbol: "🇱🇰 Sri Lanka" },
  { value: "St. Barthélemy", symbol: "🇧🇱 St. Barthélemy" },
  { value: "St. Helena", symbol: "🇸🇭 St. Helena" },
  { value: "St. Kitts & Nevis", symbol: "🇰🇳 St. Kitts & Nevis" },
  { value: "St. Lucia", symbol: "🇱🇨 St. Lucia" },
  { value: "St. Martin", symbol: "🇲🇫 St. Martin" },
  { value: "St. Pierre & Miquelon", symbol: "🇵🇲 St. Pierre & Miquelon" },
  {
    value: "St. Vincent & Grenadines",
    symbol: "🇻🇨 St. Vincent & Grenadines",
  },
  { value: "Sudan", symbol: "🇸🇩 Sudan" },
  { value: "Suriname", symbol: "🇸🇷 Suriname" },
  { value: "Svalbard & Jan Mayen", symbol: "🇸🇯 Svalbard & Jan Mayen" },
  { value: "Swaziland", symbol: "🇸🇿 Swaziland" },
  { value: "Sweden", symbol: "🇸🇪 Sweden" },
  { value: "Switzerland", symbol: "🇨🇭 Switzerland" },
  { value: "Syria", symbol: "🇸🇾 Syria" },
  { value: "São Tomé & Príncipe", symbol: "🇸🇹 Sao Tomé & Principe" },
  { value: "Taiwan", symbol: "🇹🇼 Taiwan" },
  { value: "Tajikistan", symbol: "🇹🇯 Tajikistan" },
  { value: "Tanzania", symbol: "🇹🇿 Tanzania" },
  { value: "Thailand", symbol: "🇹🇭 Thailand" },
  { value: "Timor-Leste", symbol: "🇹🇱 Timor-Leste" },
  { value: "Togo", symbol: "🇹🇬 Togo" },
  { value: "Tokelau", symbol: "🇹🇰 Tokelau" },
  { value: "Tonga", symbol: "🇹🇴 Tonga" },
  { value: "Trinidad & Tobago", symbol: "🇹🇹 Trinidad & Tobago" },
  { value: "Tristan da Cunha", symbol: "🇹🇦 Tristan da Cunha" },
  { value: "Tunisia", symbol: "🇹🇳 Tunisia" },
  { value: "Turkey", symbol: "🇹🇷 Turkey" },
  { value: "Turkmenistan", symbol: "🇹🇲 Turkmenistan" },
  { value: "Turks & Caicos Islands", symbol: "🇹🇨 Turks & Caicos Islands" },
  { value: "Tuvalu", symbol: "🇹🇻 Tuvalu" },
  { value: "Uganda", symbol: "🇺🇬 Uganda" },
  { value: "Ukraine", symbol: "🇺🇦 Ukraine" },
  { value: "United Arab Emirates", symbol: "🇦🇪 United Arab Emirates" },
  { value: "United Kingdom", symbol: "🇬🇧 United Kingdom" },
  { value: "Uruguay", symbol: "🇺🇾 Uruguay" },
  {
    value: "U.S. Outlying Islands",
    symbol: "🇺🇲 U.S. Outlying Islands",
  },
  { value: "U.S. Virgin Islands", symbol: "🇻🇮 U.S. Virgin Islands" },
  { value: "Uzbekistan", symbol: "🇺🇿 Uzbekistan" },
  { value: "Vanuatu", symbol: "🇻🇺 Vanuatu" },
  { value: "Vatican City", symbol: "🇻🇦 Vatican City" },
  { value: "Venezuela", symbol: "🇻🇪 Venezuela" },
  { value: "Vietnam", symbol: "🇻🇳 Vietnam" },
  { value: "Wallis & Futuna", symbol: "🇼🇫 Wallis & Futuna" },
  { value: "Western Sahara", symbol: "🇪🇭 Western Sahara" },
  { value: "Yemen", symbol: "🇾🇪 Yemen" },
  { value: "Zambia", symbol: "🇿🇲 Zambia" },
  { value: "Zimbabwe", symbol: "🇿🇼 Zimbabwe" },
];

function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function (e) {
    var a,
      b,
      i,
      val = this.value;
    /*close any already open lists of autocompleted values*/
    closeAllLists();
    if (!val) {
      return false;
    }
    currentFocus = -1;
    /*create a DIV element that will contain the items (values):*/
    a = document.createElement("DIV");
    a.setAttribute("id", this.id + "autocomplete-list");
    a.setAttribute("class", "autocomplete-items");
    /*append the DIV element as a child of the autocomplete container:*/
    this.parentNode.appendChild(a);
    /*for each item in the array...*/

    for (i = 0; i < arr.length; i++) {
      /*check if the item starts with the same letters as the text field value:*/
      if (
        arr[i].value.substr(0, val.length).toUpperCase() == val.toUpperCase()
      ) {
        /*create a DIV element for each matching element:*/
        b = document.createElement("DIV");
        /*show the symbol:*/
        b.innerHTML = arr[i].symbol;
        /*insert a input field that will hold the current array item's value:*/
        b.innerHTML += "<input type='hidden' value='" + arr[i].value + "'>";
        /*execute a function when someone clicks on the item value (DIV element):*/
        b.addEventListener("click", function (e) {
          /*insert the value for the autocomplete text field:*/
          inp.value = this.getElementsByTagName("input")[0].value;
          /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
          closeAllLists();
        });
        a.appendChild(b);
      }
    }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function (e) {
    var x = document.getElementById(this.id + "autocomplete-list");
    if (x) x = x.getElementsByTagName("div");
    if (e.keyCode == 40) {
      /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
      currentFocus++;
      /*and and make the current item more visible:*/
      addActive(x);
    } else if (e.keyCode == 38) {
      //up
      /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
      currentFocus--;
      /*and and make the current item more visible:*/
      addActive(x);
    } else if (e.keyCode == 13) {
      /*If the ENTER key is pressed, prevent the form from being submitted,*/
      e.preventDefault();
      if (currentFocus > -1) {
        /*and simulate a click on the "active" item:*/
        if (x) x[currentFocus].click();
      }
    }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = x.length - 1;
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
    closeAllLists(e.target);
  });
}
